(function () {
  "use strict";

  var studies = [
    { title: "Post-Acquisition Integration at Scale", sector: "Mergers & Acquisitions, Regulated / Compliance Services", group: "Transformation", challenge: "The UK compliance and regulatory services market is highly fragmented, and private equity-backed buy-and-build consolidation has become the dominant growth model in the sector. Platforms scale fast through acquisition, then race to integrate before the cost and culture gaps between businesses start eating the value of the deal. This was exactly that challenge, at pace: a rapidly scaling group that had grown through acquisition to 18+ individual businesses, each with its own culture, systems and ways of working, needing to become genuinely one organisation rather than a holding company of former competitors.", response: "Change Rebellion designed and embedded an enterprise-wide change framework, governance model and communications approach spanning every business unit. We built change networks across the group to carry the message locally rather than top-down, and introduced leadership engagement and behavioural alignment work to support genuinely new ways of working, not just a rebrand on top of old habits.", result: "18+ businesses unified under one framework and one governance model, with change capability embedded internally rather than left dependent on outside support—directly protecting the value case for the acquisitions themselves." },
    { title: "Field-Force Digital Rollout Recovery", sector: "Energy / Utilities, Gas Distribution", group: "Digital", challenge: "A gas distribution business serving close to 6 million homes and businesses, with a field workforce of several thousand engineers, had a digital field-force system rollout fail on them, leaving engineers without a working tool and senior leadership's confidence in the programme badly shaken. The technology wasn't the core problem; adoption and trust were.", response: "Change Rebellion took over the challenged programme and reset the adoption and stakeholder engagement strategy from the ground up. Within four weeks we'd rebuilt confidence with senior leadership. We then delivered readiness, training and mobilisation directly to field teams, culminating in a successful relaunch.", result: "A field-based workforce of several thousand engineers brought back onto a working system, within a 4-week confidence-rebuild window, with measurable improvements in both compliance and adoption following relaunch—a programme that went from written-off to delivering." },
    { title: "Global CRM Adoption Programme", sector: "Oil & Gas, Global Operations", group: "Digital", challenge: "A global energy major was rolling out Salesforce across its operations worldwide, part of a broader push across the oil and gas sector toward digitised, data-led customer and operations management. Technology alone doesn't change behaviour; adoption across multiple regions and operating cultures, each with its own priorities and pace, was the real challenge.", response: "We defined the global adoption and communications strategy, aligning it to new digital operating rhythms across every region in scope. Stakeholder engagement was run region by region to build genuine advocacy rather than compliance, backed by internal campaigns designed to make the benefits visible early rather than assumed.", result: "A genuinely global rollout spanning multiple regions and operating cultures simultaneously, with accelerated early-stage adoption and stronger benefit visibility than a standard top-down deployment would have achieved." },
    { title: "Oracle ERP Deployment Across County-Wide Services", sector: "Public Sector, Local Government", group: "Public sector", challenge: "A county council serving over 12,000 employees needed to replace an ageing Oracle system that had run its core Finance, HR, Payroll and Procurement processes for more than a decade—a system that was increasingly costly and complex to maintain, in an environment where budget pressure and public accountability make failed adoption especially visible.", response: "We led change delivery across the deployment, working through the practical realities of local government transformation: multiple service areas with different priorities, constrained resources, and staff who had seen technology promises fall short before. The focus was on building genuine buy-in service by service rather than relying on a single top-down rollout message.", result: "Core Finance, HR, Payroll and Procurement processes migrated across a workforce of 12,000+, with change discipline that now shapes how Change Rebellion approaches public sector transformation." },
    { title: "First-of-Type Digital Patient Records Transformation", sector: "Healthcare, Acute NHS Trust", group: "Public sector", challenge: "Introducing the first Epic Electronic Patient Record system into an NHS trust in the UK was a first-of-type deployment impacting over 12,000 clinical and administrative users, and by extension every patient moving through the trust's hospitals. The trust went on to become the first NHS trust in the UK to reach HIMSS Stage 7, the highest international standard for digital maturity in acute care.", response: "We led the change dimension of the original deployment: getting a workforce with deeply embedded paper- and legacy-system habits to trust, adopt and rely on a completely new digital record at scale, in an environment where errors carry real clinical risk.", result: "12,000+ users onboarded to a first-of-type national deployment, now underpinning a trust recognised as one of the most digitally mature hospital systems in Europe—a foundation-level example of what change-led digital adoption can achieve in healthcare." },
    { title: "Regulatory & IT-Led Change Across National Infrastructure", sector: "Energy, National Infrastructure", group: "Capability", challenge: "A national energy infrastructure operator needed to raise the profile and maturity of business change as a discipline in its own right—not an afterthought bolted onto IT delivery, but a capability that could be trusted to prepare the organisation for regulatory, cultural and technology-led change simultaneously, across a multi-year portfolio.", response: "We introduced a business change capability and framework from the ground up, including a new web-based change tracking tool, and built protocols for engagement to transfer change skills directly into the IT function. We set up a Change Management Office to oversee multiple system upgrades including SAP and bespoke systems and data upgrades, ran impact and readiness assessments, and made sure benefits were tracked rather than assumed.", result: "A Change Management Office set up and embedded, overseeing SAP and multiple bespoke system and data upgrades across a 2.5-year, multi-programme portfolio, with a repeatable framework and tooling left behind." },
    { title: "Global Finance Transformation, Oracle Cloud Deployment", sector: "Financial Services, Global Reinsurance", group: "Transformation", note: "Led by Change Rebellion founder Mark Green", challenge: "A global reinsurance group was moving its Life Capital finance function onto a new Oracle Cloud (SaaS) backbone, a global design programme spanning stakeholders across Luxembourg, Bratislava, the United States and the UK, covering core finance processes from procure-to-pay through to fixed assets.", response: "We were accountable for the Change & Communications Strategy, the Training Strategy and the Training Needs Assessment for the global design phase, adapting the organisation's standard Prosci-based change approach to a genuinely international, multi-site rollout. We built and ran the change agent network across Global Finance functions and reported change status and risk directly into the Project Steering Board.", result: "A change and training strategy built for a finance transformation spanning 4 countries and every core finance process, from leadership alignment through to frontline training needs." },
    { title: "Business Change Capability Build, Insurance", sector: "Financial Services, Insurance", group: "Capability", challenge: "Supporting a major insurer's End-to-End programme, where the real gap wasn't the technology roadmap—it was that business and IT teams weren't yet working from a shared change playbook.", response: "We created and implemented a Business Change Framework and associated tools, then focused on transferring the knowledge and skills needed to build lasting internal capability rather than leaving the organisation reliant on outside support. That meant assessing how business methodologies were actually being used day to day, and driving process improvement jointly across business and IT rather than treating them as separate workstreams.", result: "A Business Change Framework and toolset embedded across a major End-to-End transformation programme, with internal capability transfer built in from day one." },
    { title: "Business Change Capability & Oracle System Upgrades", sector: "Energy, Utilities", group: "Capability", challenge: "A major energy supplier's Business Energy department was running a series of Oracle and system upgrades but had no consistent change capability of its own to support them, meaning every upgrade risked reinventing the wheel on stakeholder engagement and readiness.", response: "We introduced a Business Change Model and Framework, ran organisational readiness assessments, and built a benefits tracking and recording tool the department could keep using. We managed senior stakeholder engagement directly, trained new change staff in best practice, and our founder was invited to guest-speak on the organisation's own Managing Change course for senior managers—a sign the capability had genuinely landed internally.", result: "A full change capability, model, framework, benefits tracker and trained internal staff, built and embedded across a 1-year engagement supporting multiple Oracle and system upgrades." },
    { title: "Behavioural Change Programme, Rail Infrastructure Safety", sector: "Transport, Rail Infrastructure", group: "Behaviour", challenge: "Rail infrastructure is a high-hazard environment by nature, and safety-critical behaviour change is judged not on communications output but on whether people genuinely change how they work on and around the live network. We supported delivery of a large-scale safety of works scheme across the business.", response: "We developed and managed relationships with the business community and stakeholders UK-wide, controlled programme change and risk on business change tasks, and created engagement plans following the organisation's own best-practice programme methodology. Central to the role was setting realistic expectations on both the benefits and drawbacks of specific changes, and managing risk to benefits realisation and stakeholder engagement throughout.", result: "Stakeholder engagement and change delivery run UK-wide across a safety-critical behavioural change programme spanning 16 months, in an industry where the cost of getting adoption wrong is measured in safety incidents, not just missed KPIs." },
    { title: "Digital Workplace Rollout, Water & Utilities", sector: "Utilities, Water", group: "Digital", challenge: "A major water utility needed to complete a desktop refresh project mid-flight, moving end users from legacy Windows and multiple versions of Microsoft Office onto Windows 7 and Office 365, including mobile working and device rollout for frontline and off-site teams such as call centre staff and water and wastewater field workers.", response: "We stepped in mid-programme to maintain delivery consistency and hold existing timelines and milestones, while driving reduction and standardisation of the applications estate. We engaged directly with key business areas, including call centres and off-site workers, on change readiness and planning for the new ways of working.", result: "Approximately 7,500 end users migrated to Windows 7 and Office 365, including mobile working rollout, delivered without missing the programme's existing key milestones." },
    { title: "Records Management Transformation, Central Government", sector: "Public Sector, Central Government", group: "Public sector", challenge: "A short, focused engagement leading an Electronic Document and Records Management project for a UK government agency—the kind of unglamorous but essential public sector change work that underpins how government departments actually manage information day to day.", response: "Engagement was run directly with the teams who owned the records day to day, spanning the agency's UK-wide offices. We mapped how documents actually moved through the organisation, then shaped retention, filing and retrieval around that reality. Staff joined the design conversation early, and communication and training were phased alongside rollout so each team got support when it was needed.", result: "A records management process redesigned around staff spread across the agency's UK-wide offices, not just its headquarters, with engagement run team by team rather than through a single central briefing." }
  ];

  var industries = [
    "Mergers & Acquisitions",
    "Energy / Utilities",
    "Oil & Gas",
    "Public Sector",
    "Healthcare",
    "National Infrastructure",
    "Financial Services",
    "Insurance",
    "Energy / Utilities",
    "Rail Infrastructure",
    "Water & Utilities",
    "Central Government"
  ];

  studies.forEach(function (study, index) {
    study.id = index < 9 ? index + 1 : index + 2;
    study.industry = industries[index];
  });

  function pad(value) { return String(value).padStart(2, "0"); }
  function imageMarkup(study, detail) {
    return '<img src="img/case-studies/' + study.id + '.jpeg" alt="" loading="' + (detail ? 'eager' : 'lazy') + '">';
  }
  function header() {
    return '<header class="case-header"><div class="case-header-inner"><a class="case-logo" href="index.html" aria-label="Change Rebellion home"><img src="img/logo-light.png" alt="Change Rebellion"></a><button class="case-menu-button" type="button" aria-expanded="false">Menu</button><nav class="case-nav" aria-label="Main navigation"><a href="index.html">Home</a><a href="about.html">Our Story</a><a href="delivery-approach.html">Our Delivery Approach</a><a href="services.html">What We Do</a><a href="mark.html">Our Founder</a><a href="rebellion-goes-green.html">Rebellion Goes Green</a><a href="in-the-press.html">In The Press</a><a href="awards.html">Awards</a><a href="case-studies.html">Case Studies</a><a href="contact.html">Contact</a></nav></div></header>';
  }
  function footer() {
    return '<footer class="case-footer"><div class="case-shell"><div class="case-footer-cta"><div><div class="case-kicker">Start a conversation</div><div class="case-footer-title">Ready to make change <em>land?</em></div></div><a class="case-footer-link" href="contact.html" aria-label="Contact Change Rebellion"><span class="case-diagonal-arrow" aria-hidden="true"></span></a></div><div class="case-footer-meta"><span>&copy; 2026 Change Rebellion</span><span>Honesty. Empathy. Change that sticks.</span></div></div></footer>';
  }
  function bindMenu() {
    var button = document.querySelector('.case-menu-button');
    var nav = document.querySelector('.case-nav');
    if (!button || !nav) return;
    button.addEventListener('click', function () {
      var open = nav.classList.toggle('is-open');
      button.setAttribute('aria-expanded', String(open));
      button.textContent = open ? 'Close' : 'Menu';
    });
  }
  function card(study, index) {
    return '<article class="case-card" id="case-study-' + study.id + '"><a class="case-card-link" href="case-study-' + study.id + '.html"><div class="case-card-image">' + imageMarkup(study, false) + '<span class="case-card-index">' + pad(index + 1) + ' / ' + studies.length + '</span><span class="case-card-arrow"><span class="case-diagonal-arrow" aria-hidden="true"></span></span></div><div class="case-card-copy"><div class="case-card-sector">' + study.industry + '</div><h2 class="case-card-title">' + study.title + '</h2></div></a></article>';
  }
  function industryLink(study, index) {
    return '<a href="#case-study-' + study.id + '" aria-label="Go to ' + study.title + '"><span>' + pad(index + 1) + '</span>' + study.industry + '</a>';
  }
  function renderLibrary() {
    var app = document.getElementById('case-app');
    if (!app) return;
    app.innerHTML = header() + '<main><section class="case-library-hero"><div class="case-shell"><div class="case-kicker">Change Rebellion / Case Studies</div><h1 class="case-library-title">Change at scale.</em></h1><div class="case-hero-bottom"><p class="case-hero-intro">Real transformations. Complex organisations. Change delivered across sector, system and scale.</p><div class="case-scroll-cue">Scroll to explore <span class="case-down-arrow" aria-hidden="true"></span></div></div></div></section><section class="case-library"><div class="case-shell"><div class="case-toolbar"><div class="case-count"><strong>' + studies.length + '</strong> engagements</div><nav class="case-industries" aria-label="Jump to a case study by industry">' + studies.map(industryLink).join('') + '</nav></div><div class="case-grid">' + studies.map(card).join('') + '</div></div></section></main>' + footer();
    bindMenu();
  }
  function renderDetail() {
    var app = document.getElementById('case-detail-app');
    var id = Number(document.body.dataset.caseId);
    var studyIndex = studies.findIndex(function (item) { return item.id === id; });
    var study = studies[studyIndex];
    if (!app || !study) return;
    var prev = studies[(studyIndex - 1 + studies.length) % studies.length];
    var next = studies[(studyIndex + 1) % studies.length];
    app.innerHTML = header() + '<main><section class="case-detail-hero"><div class="case-detail-media">' + imageMarkup(study, true) + '</div><div class="case-detail-heading"><div class="case-detail-number">Case study ' + pad(studyIndex + 1) + ' / ' + studies.length + '</div><h1 class="case-detail-title">' + study.title + '</h1><div class="case-detail-sector"><span>Sector</span>' + study.sector + '</div></div></section><section class="case-body"><div class="case-shell"><div class="case-story-grid"><div class="case-story-label">The challenge</div><div class="case-story-copy"><p>' + study.challenge + '</p></div><div class="case-story-label">Our response</div><div class="case-story-copy"><p>' + study.response + '</p></div></div><aside class="case-result"><p>' + study.result + '</p></aside></div></section><nav class="case-pagination" aria-label="Case study pagination"><a href="case-study-' + prev.id + '.html"><span class="case-pagination-label">&#8592; Previous case</span><span class="case-pagination-title">' + prev.title + '</span></a><a href="case-study-' + next.id + '.html"><span class="case-pagination-label">Next case &#8594;</span><span class="case-pagination-title">' + next.title + '</span></a></nav></main>' + footer();
    bindMenu();
  }
  renderLibrary();
  renderDetail();
}());
